version: 2.0

defaults: &defaults
  working_directory: /workspace/circleci-docker
  docker:
    - image: debian:buster-slim

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: stable
      - run:
          name: Build circleci-docker Docker image
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            docker build --tag integromat/circleci-docker:latest .
      - deploy:
          name: Push circleci-docker to Docker registry
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
            docker push "integromat/circleci-docker:latest"

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-default
